### ISSUE TITLE
Caps sensitive user-agent field causing issues

### ISSUE THREAD

**Issue by rbedfordpro** [b4dnewz/robots-parse#3]
Currently in robots-parse/lib/parser.js:
Line 2: agents: /([Uu]ser-agent:) (.+)/,

-- doesn't handle cases where user has manually typed in User-Agent (capital A). Causes error and exit.

FIX: 
Line 2: agents: /([Uu]ser-[Aa]gent:) (.+)/,

**Comment by b4dnewz** [comment]
I don't think this fix is needed since the robots keywords are case sensitive.
To be more reliable as possible only "valid" fields are parsed.
But some crawlers may auto-correct spelling issues as described in [google robots specification](https://developers.google.com/search/reference/robots_txt)

Sorry for the late reply.
